name: golf_game_play
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  google_fonts: ^6.2.1
  get_storage: ^2.1.1
  jwt_decoder: ^2.0.1
  flutter_spinkit: ^5.2.1
  lottie: ^3.1.3
  flutter_html: ^3.0.0-alpha.6
  shimmer: ^3.0.0
  shared_preferences:
  flutter_screenutil:
  flutter_svg:
  intl:
  image_picker:
  cached_network_image:
  circle_nav_bar:
  grouped_list:
  flutter_chat_bubble:
  socket_io_client:
  file_picker:
  http:
  mime_type:
  image:
  http_parser:
  path_provider:
  permission_handler:
  google_maps_flutter:
  geolocator:
  geocoding:
  mime: ^2.0.0
  carousel_slider: ^5.0.0
  pin_code_fields: ^8.0.1
  dartz: ^0.10.1
  url_launcher: ^6.3.1
  pdf: ^3.10.4
  printing: ^5.11.0
  share_plus:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # ADD THIS

# Icon configuration
flutter_launcher_icons:  # CHANGE from flutter_icons
  android: true
  ios: true
  image_path: "assets/icons/golf_logo2.png"

  # Android adaptive icon
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/golf_logo2.png"

  # iOS
  remove_alpha_ios: true

  # Web (optional)
  web:
    generate: true
    image_path: "assets/icons/golf_logo2.png"

flutter:
  uses-material-design: true

  assets:
    - assets/language/
    - assets/icons/
    - assets/icons/golf_logo2.png
    - assets/image/
    - assets/lotti/

  fonts:
    - family: Schuyler
      fonts:
        - asset: assets/font/Outfit-Medium.ttf
    - family: DMSans
      fonts:
        - asset: assets/font/DMSans-Medium.ttf